-- Manual SQL — apply with: psql $DATABASE_URL_DIRECT -f src/db/migrations/9999_triggers.sql
-- This file is NOT generated by drizzle-kit and is NOT tracked in meta/_journal.json.
-- It complements drizzle migrations and must be applied AFTER 0000-0004.

-- Generic updated_at trigger
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER profiles_set_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- on_auth_user_created: create profile placeholder
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  generated_username text;
BEGIN
  generated_username := split_part(NEW.email, '@', 1) || '_' || substr(NEW.id::text, 1, 4);

  INSERT INTO public.profiles (
    id, username, birth_date, birth_city, birth_country,
    birth_lat, birth_lng, birth_tz
  ) VALUES (
    NEW.id,
    generated_username,
    '1900-01-01',
    'PLACEHOLDER',
    'BR',
    0, 0,
    'America/Sao_Paulo'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
